#!/bin/bash

#SBATCH --partition gpu
#SBATCH --nodes 1
#SBATCH --gpus 1
#SBATCH --job-name Measurements
#SBATCH --time 02:00:00
#SBATCH --mem 32G
#SBATCH --output slurm/outputs/run_%A.out

source ./slurm/.secrets

module purge
module load 2022
module load Anaconda3/2022.05
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0
module load Java/11.0.16

source activate pex

srun python -u run/save_session_measurements.py

