#!/bin/bash

#SBATCH --partition gpu
#SBATCH --nodes 1
#SBATCH --gpus 1
#SBATCH --job-name Train_DialoGPT
#SBATCH --time 2:00:00
#SBATCH --mem 32G
#SBATCH --output slurm/outputs/train_%A.out

source ./slurm/.secrets

module purge
module load 2022
module load Anaconda3/2022.05
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0

source activate pex

#Copy data dir  to scratch
cp -r data  "$TMPDIR"/data
mkdir "$TMPDIR"/logs
mkdir "$TMPDIR"/checkpoints

echo START
date

srun python -u run/main.py \
	--task dialog  \
        --basedir msc/msc_dialogue/  \
        --sessions 1 \
        --speaker_prefixes \<self\> \<other\> \
        --add_tokens \<self\> \<other\> \
        --include_persona \
        --train_samples 6400 \
        --valid_samples 200 \
        --test_samples 20 \
        --model dialogpt \
        --lm microsoft/DialoGPT-small \
        --decoder_max 30 \
        --batch_size 16  \
        --learning_rate 0.00005 \
        --epochs 1  \
        --patience 4 \
        --log_interval 5 \
	--valid_interval 25 \
        --device cuda  \
        --loglevel INFO  \
        --logdir "$TMPDIR"/logs/  \
	--datadir "$TMPDIR"/data/ \
        --checkpoint_dir "$TMPDIR"/checkpoints/ \
        --save test_dgpt_sp  \
        --use_wandb 

cp "$TMPDIR"/logs/* ./logs
cp "$TMPDIR"/checkpoints/* ./checkpoints

echo FINISH
date