#!/bin/bash

#SBATCH --partition gpu
#SBATCH --nodes 1
#SBATCH --gpus 1
#SBATCH --job-name Train_DialoGPT
#SBATCH --time 2:00:00
#SBATCH --mem 32G
#SBATCH --output slurm/outputs/train_%A.out

source ./slurm/.secrets

module purge
module load 2022
module load Anaconda3/2022.05
module load PyTorch/1.12.0-foss-2022a-CUDA-11.7.0

source activate pex

#Copy data dir  to scratch
cp -r data  "$TMPDIR"/data
mkdir "$TMPDIR"/logs
mkdir "$TMPDIR"/checkpoints
cp ./checkpoints/trained_base_reweighted_bart* "$TMPDIR"/checkpoints

echo START
date

srun python -u run/main.py train dialogpt dialog \
        --basedir msc/msc_dialogue/  \
        --session 4 \
	--speaker_prefixes \<other\> \<self\> \
	--sessionbreak \<session\> \
	--include_history \
	--include_persona \
	--persona_selector preprocessed:trained_base_reweighted_bart \
	--augmented \
	--input_order history-personas-current \
	--valid_samples 200 \
        --test_samples 100 \
        --lm gpt2 \
        --decoder_max 30 \
        --batch_size 8  \
        --learning_rate 0.00005 \
        --epochs 1 \
        --patience 4 \
        --log_interval 10 \
	--valid_interval 25 \
        --device cuda  \
        --loglevel VERBOSE \
        --logdir "$TMPDIR"/logs/  \
	--datadir "$TMPDIR"/data/ \
        --checkpoint_dir "$TMPDIR"/checkpoints/ \
        --save trained_hfb_hpc_s4  \
	--seed 2206 \

cp "$TMPDIR"/logs/* ./logs
cp "$TMPDIR"/checkpoints/* ./checkpoints
cp "$TMPDIR"/data/msc/msc_dialogue/preprocessed* ./data/msc/msc_dialogue

echo FINISH
date
